#!/usr/bin/env python3
"""
Telegram Referral Bot Setup Script
This script helps you set up the bot with proper configuration.
"""

import os
import sys
import subprocess
import shutil

def check_python_version():
    """Check if Python version is compatible"""
    if sys.version_info < (3, 7):
        print("❌ Error: Python 3.7 or higher is required")
        print(f"Current version: {sys.version}")
        return False
    print(f"✅ Python version: {sys.version.split()[0]}")
    return True

def install_requirements():
    """Install required packages"""
    print("\n📦 Installing required packages...")
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
        print("✅ Requirements installed successfully")
        return True
    except subprocess.CalledProcessError:
        print("❌ Failed to install requirements")
        return False
    except FileNotFoundError:
        print("❌ requirements.txt not found")
        return False

def create_config():
    """Create configuration file from template"""
    print("\n⚙️ Setting up configuration...")
    
    if os.path.exists("config.py"):
        response = input("config.py already exists. Do you want to overwrite it? (y/N): ")
        if response.lower() != 'y':
            print("✅ Keeping existing config.py")
            return True
    
    # Get configuration from user
    print("\nPlease provide the following information:")
    
    bot_token = input("🤖 Bot Token (from @BotFather): ").strip()
    if not bot_token:
        print("❌ Bot token is required")
        return False
    
    channel_id = input("📢 Channel ID or username (e.g., @mychannel or -1001234567890): ").strip()
    if not channel_id:
        print("❌ Channel ID is required")
        return False
    
    admin_id = input("👑 Your Telegram User ID (get from @userinfobot): ").strip()
    try:
        admin_id = int(admin_id)
    except ValueError:
        print("❌ Admin ID must be a number")
        return False
    
    # Create config file
    config_content = f'''import os

# Telegram Referral Bot Configuration
# Generated by setup script

# =============================================================================
# REQUIRED CONFIGURATION
# =============================================================================

# Your bot token from @BotFather
# Use environment variable for security or fallback to the provided value
BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "{bot_token}")

# Your channel username (with @) or channel ID
CHANNEL_ID = os.environ.get("TELEGRAM_CHANNEL_ID", "{channel_id}")

# Your Telegram user ID (get it from @userinfobot)
ADMIN_USER_ID = int(os.environ.get("TELEGRAM_ADMIN_USER_ID", "{admin_id}"))

# =============================================================================
# OPTIONAL CONFIGURATION
# =============================================================================

# Database file name
DATABASE_NAME = "referral_bot.db"

# Maximum number of users to show in /topusers command
MAX_TOP_USERS = 50

# Default number of users to show in leaderboard
DEFAULT_LEADERBOARD_SIZE = 10

# Welcome message customization
WELCOME_MESSAGE_NEW = """Welcome to the Referral Bot, {{first_name}}! 🎉

Your unique invite link: {{invite_link}}

📢 Share this link to invite others to our channel!
🏆 The more people you refer, the higher you\'ll rank!

Use the buttons below to check your stats and leaderboard."""

WELCOME_MESSAGE_RETURNING = """Welcome back, {{first_name}}! 🎉

Your referrals: {{referral_count}}
Your invite link: {{invite_link}}

Share your link to get more referrals!"""

# Success message when someone gets referred
REFERRAL_SUCCESS_MESSAGE = "🎉 Great! {{first_name}} joined using your referral link!\\nYour total referrals: {{referral_count}}"

# Help message
HELP_MESSAGE = """🤖 Referral Bot Help

📋 Available Commands:
/start - Start the bot and get your invite link
/help - Show this help message

🎯 How it works:
1. Use /start to get your unique invite link
2. Share your link with friends
3. When someone joins the channel using your link, you get a referral point
4. Check the leaderboard to see your ranking

🏆 The users with the most referrals will be eligible for giveaways!

💡 Tip: Share your link on social media, groups, or with friends to get more referrals!"""

# Admin help addition
ADMIN_HELP_ADDITION = """\n\n👑 Admin Commands:
/adminstats - View bot statistics
/topusers [number] - View top users for giveaway
/broadcast <message> - Send message to all users"""

# Error messages
ERROR_MESSAGES = {{
    "not_admin": "❌ You\'re not authorized to use this command.",
    "invite_link_failed": "❌ Sorry, I couldn\'t create your invite link. Please make sure I\'m an admin in the channel.",
    "user_not_found": "❌ User data not found. Please use /start first.",
    "no_referrals": "📊 No referrals yet. Be the first to start referring!",
    "no_users": "📊 No users found."
}}

# =============================================================================
# ADVANCED CONFIGURATION
# =============================================================================

# Logging configuration
LOG_LEVEL = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
LOG_FORMAT = \'%(asctime)s - %(name)s - %(levelname)s - %(message)s\'

# Database connection settings
DB_CHECK_SAME_THREAD = False
DB_TIMEOUT = 30

# Telegram API settings
TELEGRAM_READ_TIMEOUT = 30
TELEGRAM_WRITE_TIMEOUT = 30
TELEGRAM_CONNECT_TIMEOUT = 30

# Rate limiting (messages per second)
RATE_LIMIT = 30

# Maximum message length before splitting
MAX_MESSAGE_LENGTH = 4000

# Invite link settings
INVITE_LINK_MEMBER_LIMIT = None
INVITE_LINK_NAME_TEMPLATE = "Referral by {{display_name}}"
'''
    
    try:
        with open("config.py", "w") as f:
            f.write(config_content)
        print("✅ Configuration file created successfully")
        
        # Create .env file sample
        env_content = f'''# Environment variables for Telegram Referral Bot
# For better security, set these environment variables instead of hardcoding values in config.py
# You can source this file or set these variables in your system

TELEGRAM_BOT_TOKEN="{bot_token}"
TELEGRAM_CHANNEL_ID="{channel_id}"
TELEGRAM_ADMIN_USER_ID="{admin_id}"
'''
        with open(".env.sample", "w") as f:
            f.write(env_content)
        print("✅ Created .env.sample file for reference")
        
        return True
    except Exception as e:
        print(f"❌ Failed to create config file: {e}")
        return False

def check_bot_files():
    """Check if all required files exist"""
    print("\n📁 Checking required files...")
    
    required_files = [
        "telegram_referral_bot_improved.py",
        "requirements.txt",
        "config.py"
    ]
    
    missing_files = []
    for file in required_files:
        if os.path.exists(file):
            print(f"✅ {file}")
        else:
            print(f"❌ {file} (missing)")
            missing_files.append(file)
    
    if missing_files:
        print(f"\n❌ Missing files: {', '.join(missing_files)}")
        return False
    
    return True

def show_next_steps():
    """Show what to do next"""
    print("\n" + "="*50)
    print("🎉 Setup completed successfully!")
    print("="*50)
    print("\n📋 Next steps:")
    print("\n1. 🤖 Add your bot to your Telegram channel:")
    print("   - Go to your channel")
    print("   - Add the bot as an administrator")
    print("   - Give it permission to 'Invite users via link'")
    
    print("\n2. 🔐 Set environment variables for better security (recommended):")
    print("   - Create a .env file based on .env.sample")
    print("   - Or set system environment variables:")
    print("     export TELEGRAM_BOT_TOKEN='your_bot_token'")
    print("     export TELEGRAM_CHANNEL_ID='your_channel_id'")
    print("     export TELEGRAM_ADMIN_USER_ID='your_admin_id'")
    
    print("\n3. 🚀 Start the bot:")
    print("   python start_bot.py")
    
    print("\n4. 🧪 Test the bot:")
    print("   - Send /start to your bot in Telegram")
    print("   - Check if you get your invite link")
    
    print("\n5. 📊 Admin commands:")
    print("   - /adminstats - View bot statistics")
    print("   - /topusers - View top referrers")
    print("   - /broadcast <message> - Send message to all users")
    
    print("\n💡 Tips:")
    print("   - Keep the bot running 24/7 for best results")
    print("   - Monitor logs for any issues")
    print("   - Backup your database file regularly")
    print("\n🆘 Need help? Check README.md for troubleshooting")

def main():
    """Main setup function"""
    print("🤖 Telegram Referral Bot Setup")
    print("="*40)
    
    # Check Python version
    if not check_python_version():
        return
    
    # Install requirements
    if not install_requirements():
        return
    
    # Create configuration
    if not create_config():
        return
    
    # Check all files
    if not check_bot_files():
        return
    
    # Show next steps
    show_next_steps()

if __name__ == "__main__":
        main()